sudo: required
language: generic
services: 
  - docker

before_install: 
  - docker build -t abdallasrouji/multi-docker -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true abdallasrouji/multi-docker npm run test

after_success: 
  - docker build -t abdallasrouji/multi-client:latest ./client
  - docker build -t abdallasrouji/multi-nginx:latest ./nginx
  - docker build -t abdallasrouji/multi-server:latest ./server
  - docker build -t abdallasrouji/multi-worker:latest ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push abdallasrouji/multi-client:latest
  - docker push abdallasrouji/multi-nginx:latest
  - docker push abdallasrouji/multi-server:latest
  - docker push abdallasrouji/multi-worker:latest
# deploy: 
#   provider: elasticbeanstalk
#   region: "eu-west-1"
#   app: "multi-docker"
#   env: "Dockerreact-env-1"
#   bucket_name: "elasticbeanstalk-eu-west-1-215258518555"
#   bucket_path: "multi-docker"
#   on: 
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY