sudo: required
language: generic
services: 
  - docker

before_install: 
  - docker build -t abdallasrouji/multi-docker -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true abdallasrouji/multi-docker npm run test

after_success: 
  - docker build -t abdallasr/multi-client ./client
  - docker build -t abdallasr/multi-nginx ./nginx
  - docker build -t abdallasr/multi-server ./server
  - docker build -t abdallasr/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push abdallasr/multi-client
  - docker push abdallasr/multi-nginx
  - docker push abdallasr/multi-server
  - docker push abdallasr/multi-worker
deploy: 
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "multi-docker"
  env: "Multidocker-env-1"
  bucket_name: "elasticbeanstalk-eu-west-1-215258518555"
  bucket_path: "multi-docker"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY